# Generated by Django 3.1.7 on 2021-02-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=1024)),
                ('keyword', models.CharField(max_length=128)),
                ('position', models.IntegerField(default=0, null=True)),
                ('url', models.CharField(max_length=1024, null=True)),
                ('title', models.CharField(max_length=2048)),
                ('traffic_index', models.IntegerField(default=0, null=True)),
                ('search_volume', models.IntegerField(default=0)),
                ('trend', models.IntegerField(default=0)),
                ('integration', models.CharField(default=None, max_length=2048, null=True)),
                ('cpc', models.FloatField(default=0.0)),
                ('competition', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Domain Data Keyword',
                'unique_together': {('domain', 'keyword', 'url')},
            },
        ),
    ]
